services:

  db:
    image: postgis/postgis:17-3.5   # stable version
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "54321:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data    # volume for persistance
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # point Docker to the init file (read only)

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432   # container port for db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./api:/app
      
volumes:
  postgres_data:

# docker compose --build
# docker compose --watch
# docker compose config     | check the config
# docker compose ps         | check ports
# docker compose build --no-cache api | build without python requirements cache

# docker compose down -v    | also removes volumes
# sudo rm -rf .geoserver/   | removes volume by force

# http://localhost:8000

# . .venv/bin/activate