services:
  ol:
    build: .
    ports:
      - 5173:5173
    volumes:
      - ./src/index.html:/usr/app/index.html
      - ./src/main.js:/usr/app/main.js
  
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=7311
    ports:
      - 54321:5432    # hostmachine:container
    volumes:
      - ./dbdata:/var/lib/postgresql     # alle data wordt ook opgeslagen op de host